-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })


-- =========================
-- DMS Startup
-- =========================

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("systemctl --user start hyprland-session.target")
    hl.exec_cmd("kdeconnectd")
end)

-- =========================
-- Hyprland Config
-- =========================

require("modules.general")
require("modules.environment")
require("modules.decoration")
require("modules.animations")

-- =========================
-- DMS Modules
-- =========================

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")
