-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("ALT + Print")
hl.bind("ALT + Print", hl.dsp.exec_cmd("dms screenshot window"), { description = "Take a Window Screenshot" })
hl.unbind("ALT + XF86AudioLowerVolume")
hl.bind("ALT + XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call mpris decrement 5"), { locked = true, repeating = true, description = "Decrease Player Volume" })
hl.unbind("ALT + XF86AudioMute")
hl.bind("ALT + XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio micmute"), { locked = true, description = "Mute Mic" })
hl.unbind("ALT + XF86AudioRaiseVolume")
hl.bind("ALT + XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call mpris increment 5"), { locked = true, repeating = true, description = "Increase Player Volume" })
hl.unbind("ALT + space")
hl.bind("ALT + space", hl.dsp.exec_cmd("dms ipc call spotlight-bar toggle"), { description = "Toggle Spotlight Bar" })
hl.unbind("CTRL + Print")
hl.bind("CTRL + Print", hl.dsp.exec_cmd("dms screenshot full"), { description = "Take a Full Screenshot" })
hl.unbind("CTRL + SHIFT + R")
hl.bind("CTRL + SHIFT + R", hl.dsp.exec_cmd("dms ipc call workspace-rename open"), { description = "Rename Workspace" })
hl.unbind("Print")
hl.bind("Print", hl.dsp.exec_cmd("dms screenshot"), { description = "Take a Screenshot" })
hl.unbind("SUPER + ALT + L")
hl.bind("SUPER + ALT + L", hl.dsp.exec_cmd("dms ipc call lock lock"), { description = "Lock" })
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.exec_cmd("dms ipc call inhibit toggle"), { description = "Toggle Caffeine" })
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("dms ipc call processlist focusOrToggle"), { description = "Toggle System Monitor" })
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"), { description = "Toggle Notifications" })
hl.unbind("SUPER + P")
hl.bind("SUPER + P", hl.dsp.exec_cmd("dms ipc outputs cycleProfile"), { description = "Cycle Profiles" })
hl.unbind("SUPER + SHIFT + N")
hl.bind("SUPER + SHIFT + N", hl.dsp.exec_cmd("dms ipc call notepad toggle"), { description = "Toggle Notepad" })
hl.unbind("SUPER + SHIFT + Slash")
hl.bind("SUPER + SHIFT + Slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"), { description = "Toggle Keybinds Cheetsheet" })
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("dms ipc call window-rules toggle"), { description = "Create New Window Rule" })
hl.unbind("SUPER + TAB")
hl.bind("SUPER + TAB", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"), { description = "Toggle Overview" })
hl.unbind("SUPER + V")
hl.bind("SUPER + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"), { description = "Toggle Clipboard" })
hl.unbind("SUPER + X")
hl.bind("SUPER + X", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Toggle PowerMenu" })
hl.unbind("SUPER + comma")
hl.bind("SUPER + comma", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"), { description = "Launch Settings" })
hl.unbind("SUPER + space")
hl.bind("SUPER + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"), { description = "Toggle Spotlight" })
hl.unbind("XF86AudioLowerVolume")
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 3"), { locked = true, repeating = true, description = "Decrease Audio" })
hl.unbind("XF86AudioMute")
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true, description = "Mute Music" })
hl.unbind("XF86AudioNext")
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("dms ipc call mpris next"), { locked = true, description = "Next Song" })
hl.unbind("XF86AudioPause")
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("dms ipc call mpris playPause"), { locked = true, description = "Toggle Music" })
hl.unbind("XF86AudioPrev")
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("dms ipc call mpris previous"), { locked = true, description = "Previous Song" })
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 3"), { locked = true, repeating = true, description = "Increase Audio" })
hl.unbind("SUPER + ALT + S")
hl.bind("SUPER + ALT + S", hl.dsp.window.move({ workspace = "special:Music", follow = false }), { description = "Move to Special Workspace Music" })
hl.unbind("SUPER + CTRL + S")
hl.bind("SUPER + CTRL + S", hl.dsp.window.move({ workspace = "special:Files" }), { description = "Move to Special Workspace Files" })
hl.unbind("SUPER + Page_Down")
hl.bind("SUPER + Page_Down", hl.dsp.focus({ workspace = "e+1" }), { description = "Open Next Workspace" })
hl.unbind("SUPER + Page_Up")
hl.bind("SUPER + Page_Up", hl.dsp.focus({ workspace = "e-1" }), { description = "Open Previous Workspace" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.workspace.toggle_special("Music"), { description = "Toggle Special Workspace Music" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.workspace.toggle_special("Files"), { description = "Toggle Special Workspace Files" })
hl.unbind("SUPER + CTRL + right")
hl.bind("SUPER + CTRL + right", hl.dsp.focus({ monitor = "r" }), { description = "Focus Center Monitor" })
hl.unbind("SUPER + SHIFT + down")
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }), { description = "Move Window Down" })
hl.unbind("SUPER + SHIFT + left")
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }), { description = "Move Window to Left" })
hl.unbind("SUPER + SHIFT + right")
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }), { description = "Move Window to Right" })
hl.unbind("SUPER + SHIFT + up")
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }), { description = "Move Window Up" })
hl.unbind("SUPER + code:20")
hl.bind("SUPER + code:20", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { description = "Expand Window Left" })
hl.unbind("SUPER + code:21")
hl.bind("SUPER + code:21", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { description = "Shrink Window Left" })
hl.unbind("SUPER + mouse:272")
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { description = "Move Window" })
hl.unbind("SUPER + mouse:273")
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { description = "Resize Window" })
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("helium-browser"), { description = "Launch Browser" })
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("org.signal.Signal"), { description = "Launch Signal" })
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("nautilus"), { description = "Launch File Manager" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("ghostty"), { description = "Launch Terminal" })
hl.unbind("SUPER + Z")
hl.bind("SUPER + Z", hl.dsp.exec_cmd("/storage/Apps/Godot/Source/bin/godot.linuxbsd.editor.x86_64.llvm"), { description = "Launch Godot" })
hl.unbind("SUPER + SHIFT + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exit(), { description = "Exit Hyprland" })
hl.unbind("SUPER + SHIFT + P")
hl.bind("SUPER + SHIFT + P", hl.dsp.dpms({ action = "toggle" }), { description = "DPMS Toggle" })
hl.unbind("CTRL + XF86AudioLowerVolume")
hl.unbind("CTRL + XF86AudioRaiseVolume")
hl.unbind("SUPER + CTRL + F")
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle Maximization" })
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Toggle Fullscreen" })
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.close(), { description = "Close Window" })
hl.unbind("SUPER + R")
hl.bind("SUPER + R", hl.dsp.layout("togglesplit"), { description = "Toggle Split" })
hl.unbind("SUPER + SHIFT + F")
hl.unbind("SUPER + SHIFT + T")
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.window.float({ action = "toggle" }), { description = "(Un)Float a Window" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc wallpaperCarousel toggle"), { description = "Toggle Wallpaper Carousel" })
hl.unbind("SUPER + Y")
hl.unbind("XF86AudioMicMute")
hl.unbind("XF86MonBrightnessDown")
hl.unbind("XF86MonBrightnessUp")
